import type { Metadata } from 'next'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Inter } from 'next/font/google'
import { Button } from '@/components/ui/button'
import './globals.css'
import { cn } from '@/lib/utils'
import { HeartIcon } from '@/components/icons/heart'
import Link from 'next/link'
import { FolderIcon } from '@/components/icons/folder'
import { Folder } from './albums/page'
import cloudinary from 'cloudinary'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function SideMenu() {
  const { folders } = (await cloudinary.v2.api.root_folders()) as {
    folders: Folder[]
  }

  return (
    <div className="pb-12 w-1/4">
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Manage
          </h2>
          <div className="space-y-1">
            <Button
              variant="ghost" // want to use secondary
              className="w-full justify-start flex gap-2"
              asChild
            >
              <Link href={'/gallery'}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z"
                  />
                </svg>
                Gallery
              </Link>
            </Button>
            <Button
              variant="ghost"
              className="w-full justify-start flex gap-2"
              asChild
            >
              <Link href={'/albums'}>
                <FolderIcon />
                Albums
              </Link>
            </Button>
            {folders.map((folder) => (
              <Button
                variant={'ghost'}
                key={folder.name}
                asChild
                className="w-full justify-start flex gap-2"
              >
                <Link href={`/albums/${folder.path}`} className="pl-8">
                  {folder.name}
                </Link>
              </Button>
            ))}
            <Button
              variant="ghost"
              className="w-full justify-start flex gap-2"
              asChild
            >
              <Link href={'/favorites'}>
                <HeartIcon />
                Favorites
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="border-b ">
          <div className="flex h-16 items-center px-4 container mx-auto">
            PHOTOS APP
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage src="https://github.com/shadcn.png" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className="flex">
          <SideMenu />
          <div className="w-full px-4 pt-8">{children}</div>
        </div>
      </body>
    </html>
  )
}
